name: work-build-nest
on:
  push:
    branches:
      - 'feature/**'
  
jobs:
  realizar-build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]

    environment: dev

    env:
      VARIAVEL_NAO_SECRETA: este é o valor de uma variável não secreta
      CODIGO_SECRETO: ${{ secrets.CODIGO_SECRETO }}
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm run build --if-present

      - run: echo 'variavel secreta:'
      - run: echo $CODIGO_SECRETO
      - run: echo 'variavel não secreta:'
      - run: echo $VARIAVEL_NAO_SECRETA
      - run: echo 'FFIMMMM'